### ISSUE TITLE
Checklist Project: Typing Game

### ISSUE THREAD

**Issue by RobsonVinicius** [RobsonVinicius/typing-game#1]
## Typing Game

- [x]  Project HTML
- [x]  Project CSS
- [x]  Word Match & Score
- [x]  Adding the Timer
- [x] Difficulty Setting
- [x] Deploy and Generating Link to live
